# Generated by Django 3.0 on 2021-04-29 12:33

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('time', models.CharField(max_length=100)),
                ('money', models.CharField(max_length=100)),
                ('alone', models.BooleanField()),
                ('group', models.BooleanField()),
                ('family', models.BooleanField()),
                ('contactsport', models.CharField(max_length=100)),
                ('how', models.CharField(max_length=100)),
                ('fitnesslevel', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('flexibility', models.BooleanField()),
                ('focus', models.BooleanField()),
                ('lower_body_strength', models.BooleanField()),
                ('balance', models.BooleanField()),
                ('endurance', models.BooleanField()),
                ('weak_speed', models.BooleanField()),
                ('weak_hand_eye_coordination', models.BooleanField()),
                ('weak_upper_body_stregth', models.BooleanField()),
                ('weak_foot_eye_coordination', models.BooleanField()),
                ('weak_being_in_water', models.BooleanField()),
                ('perfectionist', models.BooleanField()),
                ('patient', models.BooleanField()),
                ('high_energy', models.BooleanField()),
                ('competitive', models.BooleanField()),
                ('thrive_under_pressure', models.BooleanField()),
                ('tried_and_tested', models.BooleanField()),
                ('ever_changing', models.BooleanField()),
                ('centre_of_attention', models.BooleanField()),
                ('express_myself', models.BooleanField()),
                ('adrenaline_fuelled', models.BooleanField()),
                ('gender', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
