# Generated by Django 3.0 on 2021-04-29 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20210429_1239'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quiz',
            new_name='Quize',
        ),
    ]
