# Generated by Django 3.0 on 2021-05-01 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210429_1241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quize',
            old_name='lower_body_strength',
            new_name='lower_body',
        ),
        migrations.RenameField(
            model_name='quize',
            old_name='weak_upper_body_stregth',
            new_name='weak_upper_body',
        ),
    ]
