# Generated by Django 3.0 on 2021-05-01 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20210501_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quize',
            old_name='weak_being_in_water',
            new_name='being_in_water',
        ),
        migrations.RenameField(
            model_name='quize',
            old_name='weak_foot_eye_coordination',
            new_name='foot_eye_coordination',
        ),
        migrations.RenameField(
            model_name='quize',
            old_name='weak_hand_eye_coordination',
            new_name='hand_eye_coordination',
        ),
        migrations.RenameField(
            model_name='quize',
            old_name='weak_speed',
            new_name='speed',
        ),
        migrations.RenameField(
            model_name='quize',
            old_name='weak_upper_body',
            new_name='upper_body',
        ),
    ]
