# Generated by Django 3.0 on 2021-05-03 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20210501_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='quize',
            name='likely_to_recommend',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quize',
            name='selected',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
