# Generated by Django 3.0 on 2021-05-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_quize_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='likely_to_recommend',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
