# Generated by Django 3.0 on 2021-05-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_auto_20210503_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='session_key',
            field=models.CharField(max_length=300),
        ),
    ]
