# Generated by Django 3.0 on 2021-05-03 14:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_auto_20210503_1101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Enquirie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=350)),
                ('company_name', models.CharField(max_length=500)),
                ('website', models.URLField(max_length=500)),
                ('comment', models.TextField()),
            ],
        ),
    ]
