# Generated by Django 3.0 on 2021-05-05 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_enquirie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quize',
            old_name='selected',
            new_name='no',
        ),
        migrations.AddField(
            model_name='quize',
            name='yes',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
