# Generated by Django 3.0 on 2021-05-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0011_auto_20210505_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quize',
            name='no',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='quize',
            name='yes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
